### ISSUE TITLE
Multer doesn't work with my most simple app possible. No access to req.file (undefined)

### ISSUE THREAD

**Issue by madelcamp** [expressjs/multer#1066]
Hello!

Multer doesn't work with my most simple app possible. 
No access to req.file
it just throws "undefined " while trying to request with Thunder client.

![Captura de pantalla de 2022-01-19 17-14-08](https://user-images.githubusercontent.com/34782911/150206948-0299ef02-feb6-418f-a39a-92f91a76a986.png)

same issue with insomnia as client

![Captura de pantalla de 2022-01-19 17-15-00](https://user-images.githubusercontent.com/34782911/150207030-d20d0689-82ba-4979-92a1-197cd900c06d.png)

node version: v17.4.0
os: Ubuntu 20.04
express version: ^4.17.2
multer version: ^1.4.4

I'm really trying to use multer s3, but since the same issue shows up with multer, i'm writing in here instead.

I would appreciate so much your help guys with this issue.
Than you so much for your valuable work for the community!

Regards,

**Comment by abadrangui** [comment]
Note if you're using Firebase Functions,

Turns out multer doesn't work with Firebase functions like forever ([stackoverflow](https://stackoverflow.com/questions/47242340/how-to-perform-an-http-file-upload-using-express-on-cloud-functions-for-firebase))

So you need to use other packages.
I'm using express-multipart-file-parser for now
