### ISSUE TITLE
File properties

### ISSUE THREAD

**Issue by LinusU** [expressjs/multer#130]
This is what other frameworks is using for properties on uploaded files

Multer | PHP | Rails
--- | --- | ---
`fieldname` | (key) | (key)
`originalname` | `name` | `original_filename`
`name` | n/a | n/a
`encoding` | n/a | n/a
`mimetype` | `type` | `content_type`
`path` | `tmp_name` | `path`
`extension` | n/a | n/a
`size` | `size` | `size`
`truncated` | n/a | n/a
`buffer` | n/a | n/a

As I expressed in #128 I would like to get rid of `truncated`, but I also think that `name`, `encoding`, `extension` should go.

Since the new storage api actually allows people to do stuff like keeping each users files in a separate folder within the `destination` it could actually be good to know the `filename` part, maybe we should expose the following for `DiskStorage`:

```javascript
{
  filename: 'user-linus/profile.jpg',
  destination: '/var/www/uploads',
  path: '/var/www/uploads/user-linus/profile.jpg'
}
```

That way a user could quickly store the `file.filename` to the database, and then easily send that file back to another client at another time. Even if the server would move the `uploads` folder to somewhere else.

I think that `extension` should go because it's  better to encourage users to check the `mimetype` instead.

Maybe `encoding` should stay thought, anybody using it? It's form the `Content-Type` header and the spec allows basically a key-value store to be appended, we only extract `encoding` from the key-value pairs.

**Comment by jpfluger** [comment]
Regarding `name` versus `originalname`. Some users store files in one directory and sometimes these files are updates of the same file (different revision). Instead of overwriting the previous file, the user creates a new name based on Uuid, then saves both the `name` and `originalname` to a datastore.

Using error codes per https://github.com/expressjs/multer/issues/128 is good to me so to get rid of `truncated`.  If specific errors can be attributed to a single file, perhaps add and "err" object or "err.code" to the file object?  

Looking through history `encoding` is nearly non-existent. I think it is informational only. 

I'm okay with getting rid of `extension`. There are a number of user who want to control changing the extension or deleting it completely.  Another reason to keep `originalname` and allow changing of the `name` property.

**Comment by jpfluger** [comment]
Re. `name` and `extension`, see https://github.com/expressjs/multer/pull/97.

**Comment by LinusU** [comment]
Yes I can understand the need for `name`, I basically renamed it to `filename` and also added `destination` but that wasn't very clear.

**Comment by LinusU** [comment]
This is now fixed in multer `1.0.0`

**Comment by jsmunroe** [comment]
Is there not a way to keep the files in order?

**Comment by LinusU** [comment]
@jsmunroe Keep them in order how? Is this really related to this bug? Otherwise I would prefer you opening a new bug and I'll be happy to assist you with whatever problem you are having.
