### ISSUE TITLE
req object in changeDest() doesn't contain all fields.

### ISSUE THREAD

**Issue by georgemickael-b** [expressjs/multer#146]
req object in changeDest contains only the fields that are present before the last file input field and not the fields which comes after it.

**Comment by LinusU** [comment]
Thats how your browser works, it's impossible to fix in multer.

A fix for this is to use javascript on the client side to catch the submit event and instead submit using [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) and ordering the fields so that the input data is before any files.

**Comment by goowikns** [comment]
Is it possible to have an example?
