### ISSUE TITLE
Intuitive method for handling multi-part text fields

### ISSUE THREAD

**Issue by hacksparrow** [expressjs/multer#172]
@LinusU @jpfluger we need to have an intuitive method for handling text fields in multi-part forms.

Although `upload.single()`, `upload.array()`, `upload.fields()` work, it is unintuitive to call them (file handling methods) when there are no files to be uploaded.

Maybe we could extend their behavior to handle text fields?

**Comment by LinusU** [comment]
How do you mean handle them? Do you mean specify which text fields are allowed the same way we do for files?

**Comment by jpfluger** [comment]
In this situation, maybe `bodyParser.urlencoded()` would be a better fit?  Or set an option in multer or pass into `single(), array(), fields()` a param to allow all input element types except file?

**Comment by hacksparrow** [comment]
As of now, multer "seems" to be ALL about files, although it handles text fields as well (as long as it is a multi-part form). Let's not leave out the way it handles text fields.

@LinusU it could very well be. At the very basics, the interface for handling a text-only form should feel "natural".

@jpfluger for a text only form, urlencoded and json are the best, but you never know how someone might want to use multer for whatever reasons. We just need to do our part of providing the intuitive interface for the potential scenario :)

Adding additional methods doesn't feel right to me, extending `single()`, `array()`, `fields()` to handle text fields might be a good idea.

**Comment by gabeio** [comment]
this is what messed me up :laughing:... I probably won't be the only one when people finally update to 1.0.0 :smiley:

**Comment by jpfluger** [comment]
@hacksparrow -- maybe provide some code illustrating use? Here are the two extremes running through my head right now.... 

1.  Is the suggestion for multer to accept an "allowed fields" schema for all input types? And go so far as validating them? To what degree? 
2.  Or are you suggesting something more basic? eg only allow where fieldname is "avatar", where avatar could be any type of input field (not just "file" type).

**Comment by LinusU** [comment]
The reason we had for introducing the need to specify files before hand was because of a number of security related problems. These problems doesn't exists with text fields parsing thought.

Text fields are allocated in memory and is dropped when the request is done and often doesn't contain nearly enough data so the default limits is lower for fields. Files on the other hand are written to disk and thus will stick around after the request is completed.

I'm still a bit unsure on exactly what the use case is. As I discussed briefly with @gabeio, it might be a good idea to have something that would be equal to `.fields([])` that can be used when you only want to accept text fields.

**Comment by hacksparrow** [comment]
@jpfluger a lot could be done, but at the bare minimum, if someone decides to use multer for handling a text-only multi-part form, they should have a intuitive method for handling those fields. My concern is more about an intuitively-named API than what the API should do. The API functionality could be very basic, to begin with.

I want multer to handle this form (I won't use anything else because The FSM said so :smiley:):

```html
<form method="post" enctype="multipart/form-data">
  <input type="text" name="username" />
  <input type="text" name="areacode" />
  <input type="submit" />
</form>
```
@LinusU maybe extend the existing methods to handle text fields as well?

**Comment by LinusU** [comment]
@hacksparrow That form could be handled by the code below. Is there any validations that you want to make? Should it only allow the text fields `username` and `areacode`?

```javascript
app.post('/form', upload.fields([]), function (req, res) {
  // req.body === { username: _, areacode: _ }
})
```

**Comment by hacksparrow** [comment]
@LinusU `upload.fields([])` could be replaced with `.single()` and `.array()`, and it would still work. This makes text field parsing comes across as a secondary effect.

What is your opinion about making `.fields([])` work in the same way for both files and text fields? That way `.fields([])` would become the recommended way of handling text fields. Besides, the name "fields" sounds relevant to the text fields.

**Comment by LinusU** [comment]
Do you mean that we should require our users to specify all of the text fields as well? I'm not sure that I like that, that could be quite much job and I don't see the gain from it. What benefit would providing the fields give?

**Comment by jpfluger** [comment]
Do the docs need more clarity?  Maybe an example at the top of the readme (with the others) showing multer accepting any field except file input? (eg `.fields([])`).  Maybe a clearer explanation of logic? Such as.... when params (including empty arrays) are passed into `.fields()`, multer will then

1. if params have data (eg `.fields([{ name: 'avatar', maxCount: 1 }])`, then accept any input field of type "file" where the field is named `avatar` and accepted ALL input types not a "file" type  (eg text, checkbox, radio)
2. if params are empty (eg `.fields([])`, then do not accept any input field of type "file" but do accept all other input types that are not "file" types (eg text, checkbox, radio)

@hacksparrow  Because of the above logic, it's difficult to figure out how to incorporate non-file-input types as params to `.fields()` without breaking core logic with what was just released.  I think we'd need an option at the multer level to indicate multer would evaluate params differently. For example, `option.allFieldsValidate: true` would then require all fields to be accepted by multer to be passed as a param into `.fields()`. Wouldn't the input type be required as well, at least for the file field? Now, params would look like: `.fields([{ name: 'avatar', maxCount: 1, type: 'file' }, {name:'email'}])` and each field must be specified before multer accepts it.

**Comment by hacksparrow** [comment]
Let's keep it simple. Updating the README should do it, let me work on it.

**Comment by hacksparrow** [comment]
Ok, done.

**Comment by MotorCityCobra** [comment]
> ```js
> app.post('/form', upload.fields([]), function (req, res) {
>   // req.body === { username: _, areacode: _ }
> ```

I changed username and areacode to the names of my text fields in my html and I get...  

    ReferenceError: _ is not defined

I know this is something I should probably know, but I'm new to this backend stuff so can I have a clue please? What goes in the '_' position?

**Comment by MotorCityCobra** [comment]
> Do the docs need more clarity? Maybe an example at the top of the readme (with the others) showing multer accepting any field except file input?




Yes! I know your post was 4 years ago, but I'm using this and cannot for the life of me get text fields into my db with this.

**Comment by LinusU** [comment]
@MotorCityCobra text fields will just live on `req.body`.

In your example, you don't have to put anything where `_` is, rather you can access the properties on the body:

```js
app.post('/form', upload.fields([]), function (req, res) {
  console.log(req.body.username)
  console.log(req.body.areacode)
})
```

**Comment by anthonylan** [comment]
> @hacksparrow That form could be handled by the code below. Is there any validations that you want to make? Should it only allow the text fields `username` and `areacode`?
> 
> ```js
> app.post('/form', upload.fields([]), function (req, res) {
>   // req.body === { username: _, areacode: _ }
> })
> ```

Thanks for your reply but how do you get them to the server? Thanks
