### ISSUE TITLE
Multiple files are not uploading

### ISSUE THREAD

**Issue by GopalakrishnanK** [expressjs/multer#178]
Hi, 

I am trying to upload multiple images using multer. but when i try i get this error. 

![wer](https://cloud.githubusercontent.com/assets/10287362/8870626/04018284-320d-11e5-8502-5eb11eaad71e.PNG)

whats my problem.........?
here's my code,

HTML:::
![ert](https://cloud.githubusercontent.com/assets/10287362/8870768/0dd42c3e-320e-11e5-9acc-3b462c6920cb.PNG)

Jquery:::

![dfg](https://cloud.githubusercontent.com/assets/10287362/8870814/63c35d90-320e-11e5-96e8-c7420cedb6f8.PNG)

NODE JS:::
```javascript
// Custom Storage
var multi = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, './files/uploads/products/temp/')
  },
  filename: function (req, file, cb) {
    crypto.pseudoRandomBytes(16, function (err, raw) {
      cb(null, raw.toString('hex') + Date.now() + '.' + mime.extension(file.mimetype));
    });
  }
});

// multer variable
var tempImageUpload = multer({storage : multi}).array('photos',4);

// upload function
exports.tempUp = function(req, res) {
	tempImageUpload(req, res, function (err) {
		console.log(req.files);
        if (!err) {
            console.log("Image Uploaded");
            res.json({status: 1, error: "", message: "Images Uploaded"});  
        } else {
            console.log(err.message);
            res.json({status: 0, error: err.message, message: "file upload failed"});  
        }
    });
}
```

Thanks in advance................

**Comment by LinusU** [comment]
You Node.js code is expecting the fieldname to be `photos` for all the files. You jQuery code is sending them as `"file" + file`.

Change your `formData.append` line to read like this:

```javascript
formData.append('photos', this)
```

P.s. please post the actual code as text instead of images, it makes it much easier for me to suggest edits to it. [Read this](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) to get the syntax highlighting working.

**Comment by GopalakrishnanK** [comment]
@LinusU Hey thanks. silly mistake huhhh....... it's fixed now..........
