### ISSUE TITLE
No file uploaded but res.files not empty if limits.files reached

### ISSUE THREAD

**Issue by imShara** [expressjs/multer#232]
Shoudn't it leave `res.files` empty if no files uploaded? And how to catch this error to prevent database writing?

**Comment by LinusU** [comment]
I don't really understand, if the limit is reached you should get an error and your route shouldn't be called at all?

**Comment by imShara** [comment]
@LinusU, nope, there is no errors, even if limit is reached and route works.

**Comment by LinusU** [comment]
Well, isn't that the problem than. If the limit is reached you should get an error.

Could you post how you are using multer?

**Comment by LoicMahieu** [comment]
I think I have the same problem: when handling a too large file (due to fileSize limit), next is called without error.
I made a small repo that demonstrate it: https://github.com/LoicMahieu/test-multer

I tried to reproduce it in multer's test but without success. Maybe due to file system storage ? You will observe that the test does not fail when it upload a small file `__filename`: https://github.com/LoicMahieu/test-multer/blob/master/test/upload.js#L32

**Comment by LinusU** [comment]
Cool, this bug is caused by busboy emitting the `finish` event just after the `limits` event. Since the `limit` got stuck waiting for the pending writes to close, and the half uploaded file to be removed,  the `finish` event triggered us moving forward.

I have a fix, just need to incorporate a test that is failing into our test suite.

**Comment by LinusU** [comment]
Fixed and released as `1.0.6`, thanks for the help @LoicMahieu

**Comment by LoicMahieu** [comment]
Awesome @LinusU Thanks for fixing this issue!
