### ISSUE TITLE
Crash on .single

### ISSUE THREAD

**Issue by sebastianarena** [expressjs/multer#260]
Hi.
When using the .single function to specify that only one upload is allowed, you can make the app crash by uploading two files at the same time.
The error is as follows:

``` text
fs.js:932
  binding.unlink(pathModule._makeLong(path), req);
          ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.unlink (fs.js:932:11)
    at DiskStorage._removeFile (node_modules/multer/storage/disk.js:61:6)
    at remove (node_modules/multer/lib/make-middleware.js:64:19)
    at handleFile (node_modules/multer/lib/remove-uploaded-files.js:10:5)
    at removeUploadedFiles (node_modules/multer/lib/remove-uploaded-files.js:25:3)
    at EventEmitter.<anonymous> (node_modules/multer/lib/make-middleware.js:67:9)
    at EventEmitter.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at EventEmitter.emit (events.js:166:7)
    at EventEmitter.decrement (node_modules/multer/lib/counter.js:15:32)
    at node_modules/multer/lib/make-middleware.js:146:34
    at WriteStream.<anonymous> (node_modules/multer/storage/disk.js:43:9)
    at emitNone (events.js:72:20)
    at WriteStream.emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
```

Thanks!

**Comment by LinusU** [comment]
This is interesting, I'll try to take a look at it this weekend.

Protip, to post output, use the following syntax known as "fenced code blocks":

    ```text
    Here goes the output...
    ```

**Comment by kaminoo** [comment]
Thanks Linus! Not a lot of knowledge on Markdown! Ha

Best to you

**Comment by dbellavista** [comment]
Hi @LinusU ! I don't know if it's the same bug, but I can reproduce this error with the upload:

```
      app.put('/test', uploader.array('file'), handler);
      /* ... */
      var formData = {
        file: fs.createReadStream(p1),
        lolfiles: [
          fs.createReadStream(p2),
          fs.createReadStream(p3)
        ],
      };
```

The fileFilter function at https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L112 is called thrice, one for `file` and two for `lolfiles`. Since both `lolfiles` cause the filter function to fails, the function abortWithError at https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L59 is called twice.

But when the file is removed in https://github.com/expressjs/multer/blob/master/storage/disk.js#L59 , the path value is deleted. So on the first call you have:

```[ { fieldname: 'file',
    originalname: 'tmp_test_route',
    encoding: '7bit',
    mimetype: 'false',
    destination: '/my/very/secret/path',
    filename: 'f8fc3784d434c25d8935c29f8eaf48c7',
    path: '/my/very/secret/path/f8fc3784d434c25d8935c29f8eaf48c7',
    size: 16 } ]```

while the second call is:

```[ { fieldname: 'file',
    originalname: 'tmp_test_route',
    encoding: '7bit',
    mimetype: 'false',
    size: 16 } ]```

For now, I hotfixed this with

```
if (!path) {
  return cb();
}
```

in https://github.com/expressjs/multer/blob/master/storage/disk.js#L56

**Comment by gcaraciolo** [comment]
I can reproduce the same error if i use multer.single('image') as middleware and try a DoS sending 2 files.

**Comment by LinusU** [comment]
This is great work!

Do you think it could be solved by adding the following line to the start of `abortWithError`? https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L59

```javascript
if (errorOccured) return
```

**Comment by nickmitsh** [comment]
I believe I was uploading 2 file very fast, same issue

**Comment by kaminoo** [comment]
I don't know about the speed. I was testing it with postman for mac/chrome. I really needed a single file so I thought to test out the case for more.

**Comment by gcaraciolo** [comment]
This problem can be half solved using limits objects. Putting 
> limits: {
   files:1
}
 
the correct error is thrown (Too many files). However, if put 
> limits: {
   files: 1,
   fileSize: 2 * 1024
},

the error 
 <strong> binding.unlink(pathModule._makeLong(path), req); </strong>
appears again.

**Comment by kaminoo** [comment]
Indeed I am using the last options you described!
I didn’t try with different options as I saw no correlation between filesize and the file limits.

**Comment by gcaraciolo** [comment]
yeah, i don't understand why. I'm with the same problem.

**Comment by nickmitsh** [comment]
Oh, when I say upload 2 files, it was 2 separate uploads, not 2 files in one time.

Right now, I add this to /multer/storage/disk.js +61: 
path && fs.unlink(path, cb);

**Comment by k00k** [comment]
+1

I'm using `.single` and getting "Too many files". This is occurring across multiple separate uploads, like @nickmitsh was seeing. 

@nickmitsh - can you explain what that fix is doing that you use? `path && fs.unlink(path, cb);`

**Comment by JonathanOlesz** [comment]
Hi,
I had the same error  with multer@1.1.0 : 

```
fs.js:975
  binding.unlink(pathModule._makeLong(path), req);
          ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.unlink (fs.js:975:11)
    at DiskStorage._removeFile (/home/server/server/node_modules/multer/storage/disk.js:61:6)
    at remove (/home/server/server/node_modules/multer/lib/make-middleware.js:64:19)
    at handleFile (/home/server/server/node_modules/multer/lib/remove-uploaded-files.js:10:5)
    at removeUploadedFiles (/home/server/server/node_modules/multer/lib/remove-uploaded-files.js:25:3)
    at EventEmitter.<anonymous> (/home/server/server/node_modules/multer/lib/make-middleware.js:67:9)
    at EventEmitter.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at EventEmitter.emit (events.js:166:7)
    at EventEmitter.decrement (/home/server/server/node_modules/multer/lib/counter.js:15:32)
    at /home/server/server/node_modules/multer/lib/make-middleware.js:146:34
    at WriteStream.<anonymous> (/home/server/server/node_modules/multer/storage/disk.js:43:9)
    at emitNone (events.js:72:20)
    at WriteStream.emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
```

I added : `if (path) fs.unlink(path, cb)` in /multer/storage/disk.js +61 as suggested @nickmitsh and the bug seems fixed

 This is the good way to fix this issue ?

**Comment by cyl19910101** [comment]
I've got the same error and I've found 2 ways to reproduce the error, both using `.array('files', 3)`:

1. if you don't write some limits like fileSize or something like that, just `multer({ dest : 'uploads' })`,  then you can reproduce the error by upload more than 3 files with at least 2 mime types (at least have one file which has different type with others).

2. if you write some limits like `limits:{fileSize:1048576}`, then you can reproduce the error by upload more than 3 files with at least 1 file break the fileSize rule (in fact it break two rules), even all of then are the same type, you can still get this error.

I didn't dig much into this. Sometimes it's very wired the code works well if you upload 4 files to it(LIMIT_UNEXPECTED_FILE error will be catch by express error handler), but if you upload 5 files, then you will get this error and the program crashed.

If you output the file before `fs.unlink(path, cb)`, there's no 'path' property, I guess because it didn't success to upload? `path && fs.unlink(path, cb)` can avoid unlink undefined path, but I don't know if there's something more need to be done.

node: 5.9.0

"dependencies": {
    "express": "^4.13.4",
    "multer": "^1.1.0"
  }

OS X 10.11.3

Chrome 49

`var express = require( 'express' );`
`var multer  = require( 'multer' );`
`var fs      = require( 'fs' );`
`var app     = express();`
`var upload  = multer( { dest : 'uploads', limits : { fileSize : 1048576 } } );`

`app.get( '/', ( req, res ) => fs.createReadStream( 'index.html' ).pipe( res ) );`

`app.post( '/files', upload.array( 'files', 3 ), ( req, res ) => res.end( 'uploaded' ) );`

`app.use( ( err, req, res, next ) => res.end( err.code + '\n' + err.stack ) );`

`app.listen( 8888 );`

`<form action="/files" method="post" enctype="multipart/form-data">`
    `<input type="file" name="files" multiple> <input type="submit">`
  `</form>`
