### ISSUE TITLE
Why memoryStorage not filename (rename)?

### ISSUE THREAD

**Issue by ngthorg** [expressjs/multer#288]
i need rename with memory Storage, but it is don't support

**Comment by LinusU** [comment]
You don't have a file name when storing files in memory, they are just stored in the memory.

I think that you are misunderstanding something, what's your use case?

**Comment by Spown** [comment]
I think its somewhat related to my issue: I'm struggling to assemble an uploader, that allows me to use md5 hash of the file's content in the name, but as of now it is not possible with the standard disk storage, because if I pass the ``file.stream`` to a reader (concat-stream in my case) via ``diskStorage.filename`` callback - the stream gets read and no further events are fired [along the way](https://github.com/expressjs/multer/blob/bbca185424f6f6361ee758f510667b35d61afc8b/storage/disk.js#L42) which results in properly named, but empty files. So it's kinda architectural flaw, imo that either allows you to handle the name or the content, but not both... I'm going to write my own storage, but I think you should resolve ``file.stream`` before ``diskStorage.destination`` and ``diskStorage.filename`` and make the ``buffer`` property of the ``file`` argument always visible, not only in case of memoryStorage.

**Comment by LinusU** [comment]
@Spown The problem with the approach your describing is that it would *always* store *the entire file* in memory. That is very problematic since that could open yourself to easy DOS attacks and it's also very inefficient.

If that is what you want, use the `memoryStorage` instead of `distStorage`. That is what it's made for.

**Comment by Spown** [comment]
To avoid the _"always"_ one should consider freeing the memory at certain points. As of the _"entire file"_ - so what? I don't think DoS prevention should be handled at this level - you either employ a dedicated middle-ware on a lower level or build a storage that keeps track of the all concurerent uploads either through a centralized watcher or through gathering averything in a global queue or whatever.

The callbacks in question should give the user ["...full control on storing files to disk"](https://github.com/expressjs/multer#diskstorage). Nothing more and nothing less. Right now its not that full...

Well than again at least one can override the storage completely... I still think that exposing ``file.stream`` in the default diskStorage is wrong. I mean whats the point of exposing it anyway if almost anything you could do with it will break the flow?

**Comment by LinusU** [comment]
> To avoid the "always" one should consider freeing the memory at certain points.

With always I meant that for every file that get's uploaded we also store it in memory, even if the person using multer only wants to store it at disk.

> As of the "entire file" - so what?

Node.js has a max buffer size which would then limit the file size of uploaded files. It's also very non-performant.

> The callbacks in question should give the user "...full control on storing files to disk". Nothing more and nothing less. Right now its not that full...

I don't agree, it gives you full control of storing to disk. It doesn't give you full control on storing to memory though, that's what `memoryStorage` is for.

> Well than again at least one can override the storage completely... I still think that exposing `file.stream` in the default diskStorage is wrong. I mean whats the point of exposing it anyway if almost anything you could do with it will break the flow?

It isn't exposed. It's not in the documentation, and the property isn't enumerable. It was never meant to be used outside of the internals of multer.

**Comment by export-to-excelnate** [comment]
> [@Spown](https://github.com/Spown) The problem with the approach your describing is that it would _always_ store _the entire file_ in memory. That is very problematic since that could open yourself to easy DOS attacks and it's also very inefficient.
> 
> If that is what you want, use the `memoryStorage` instead of `distStorage`. That is what it's made for.





+1
