### ISSUE TITLE
 Cant get the middleware work in express 4 for mobile application

### ISSUE THREAD

**Issue by s1155030742** [expressjs/multer#327]
My problem is similar to #159 
[](https://github.com/expressjs/multer/issues/159)
The only difference is I am writing a controller for mobile application,
which is designed to allow user upload file to server.

So, the problem is , what is the argument in multer.single()?

**Comment by wiill** [comment]
Hi there!
I get the exact same error as @daffa2 in #159 , but only when I'm using a mobile browser, seems to have some issues depending on the browser agent: 

admin.ejs:
`<input class="text1" type="file" name="questionFile"
<input type="submit" value="Upload question file" data-icon="action"
`

routes.js
`var upload = multer({ dest: config.UPLOADS_DIR });

router.post('/file-upload', [requireAdmin], upload.single('questionFile'),function upload(req, res, next){

        try{

            // get the temporary location of the file
            var uploadedFilePath = req.file.path;

            if(req.file.mimetype.contains("csv")){
                if(req.file.size === 0)
                    fs.unlink(uploadedFilePath);
                else{
                    var previousVersion = path.join(path.dirname(uploadedFilePath) , req.file.originalname);
                    if(fs.existsSync(previousVersion)){
                        fs.unlink(previousVersion);
                    }

                    var newName = path.join(path.dirname(uploadedFilePath) , req.file.originalname);
                    fs.rename(uploadedFilePath, newName);
                }
            }else if(path.extname(uploadedFilePath) === ""){
                //EMPTY UPLOAD
                fs.unlink(uploadedFilePath);
            }

            res.redirect("/admin");
        }catch(err){
            next(err);
        }
    });`


- Safari Desktop OK
- Safari iPad OK
- Safari iPhone KO
- Chrome Desktop OK
- Chrome mobile KO
- Chrome mobile faking desktop ("View desktop version of page"): no error but no upload neither

I'll edit upon more tests...

**Comment by aaqib90** [comment]
@wiill have you found any solution ? I have same problem.

**Comment by wiill** [comment]
Hi @aaqib90, thanks for asking...

I was having 2 problems:
- I have a duplicate form on my page, but duplicated field was using a different ID, so it was mixing up and throwing the error mentioned in the title of the issue. Getting the same field ID in both forms resolved the error

- the Chrome Mobile faking desktop issue: no error but no upload either
`req.file.mimetype`
may be "csv" or "comma-separated-values" depending on the browser, and in my code, when other than "csv", router method did what it was supposed to do, i.e. nothing at all! so correcting the condition to filename.contains('csv') instead of checking the mime type did the trick

**Comment by jonchurch** [comment]
Closing as inactive. OP I hope you were able to solve your issue ❤️
