### ISSUE TITLE
Unexpected end of multipart data when upload Excel files

### ISSUE THREAD

**Issue by jderuere** [expressjs/multer#412]
Hi everyone!

I'm struggle with this error, only when I'm trying to upload an Excel file (but it's working with CSV).

Error: Unexpected end of multipart data
    at /node_modules/dicer/lib/Dicer.js:62:28

My code is based on Swagger-node, but I'm using the last version of multer :/

```
var SwaggerExpress = require('swagger-express-mw');
var app = require('express')();
var upload = require('multer')({ dest: "uploads/" });
module.exports = app; // for testing

var config = {
  appRoot: __dirname // required config
};

SwaggerExpress.create(config, function (err, swaggerExpress) {
  if (err) {
    throw err;
  }

  app.post('/api/devices/upload', upload.array('file', 1));

  // install middleware
  swaggerExpress.register(app);

  var port = process.env.PORT || 10010;
  app.listen(port);
});
```

My front-end is an Agularjs App, I'm using the angular-file-upload (https://github.com/nervgh/angular-file-upload) to create my multipart request. As I said, it's working fine with CSV, but for application type, I got the previous error.

Any idea?

**Comment by arminschleicher** [comment]
Hey  @jderuere - did you figure out what the problem was?

**Comment by ryhinchey** [comment]
@jderuere that error is coming from [Dicer](https://github.com/mscdex/dicer/blob/master/lib/Dicer.js#L61) and indicates (based on the code and this stack overflow [post](https://stackoverflow.com/questions/43905675/error-unexpected-end-of-multipart-data-in-busboy-file-upload)) that the issue is probably with the formatting of the file content.  

I'm going to go ahead and close this for now.  If you can create a reproducible example and include the file, please re-open and I'd be happy to take a look.
