### ISSUE TITLE
Multer 1.1.0 array, how to catch error when close browser

### ISSUE THREAD

**Issue by heshuguo** [expressjs/multer#456]
Using Multer 1.1,0 version to upload the files to a remote server via browser, however, when I try to close the browser during the file upload, how can I catch the error so that I can write some code to handle the error.

// upload to node
		uploadToNode: function(dest) {
			return upload.uploadFiles(dest);
		}
function uploadFiles() {
  var uploadStorage = multer.diskStorage({
    destination: function(req, file, cb){
      console.log('uploadStorage destination:', req.session.uploadFolder);
      cb(null, req.session.uploadFolder)
    },
    filename: function (req, file, cb) {
      cb(null, file.originalname);
    }
  });

  return multer({ storage: uploadStorage }).array('file');
}
router.post('/upload/:dataProcess', dal.uploadToNode(), function(req, res) {
//how to catch the error here when I close the browser during the upload.
}

**Comment by gireeshpunathil** [comment]
@heshuguo - there an `error handling` section in the bottom of the multer documentation README https://github.com/expressjs/multer that shows how to achieve this. Basically, you can call the multer middleware directly in the user callback, rather than passing the return value of it. This call's callback receives errors, if any.

Hope this helps.

fyi @LinusU - this can be closed as answered.
