### ISSUE TITLE
fileFilter should throw exception when there are none to process

### ISSUE THREAD

**Issue by dwjft** [expressjs/multer#486]
Consider:

```javascript
const fileFilter = (req, file, cb) => {
  cb(null, false);
};
const upload = multer({ fileFilter }).fields([{ name: 'file', maxCount: 1 }]);
express.post('/', upload, (req, res) => {
  req.files.file[0]; // does not exist, throws error
});
```

All files were filtered out of the request, but the request was allowed to proceed.

Expected behaviour: `multer` fails with [LIMIT_UNEXPECTED_FILE](https://github.com/expressjs/multer/blob/master/lib/make-error.js) code.

**Comment by HarshithaKP** [comment]
@dwjft fileFilter is designed to filters the files based on user defined conditions and accepts or reject based on callback defined and not meant to throw exception.

Irrespective of fileFilter operation results, request callback will be executed in response to end the  transaction with the client.

It is not a good idea to throw exception from the server, because malicious client can break the server.

**Comment by LinusU** [comment]
closing for lack of response, happy to reopen if more information surfaces
