### ISSUE TITLE
Error uploading image on server

### ISSUE THREAD

**Issue by AdrianMadalin** [expressjs/multer#561]
Hy i get an error uploading the image on the SERVER , it basically stops here : 
  upload(req, res, function (err) {
    if (err) {
      // An error occurred when uploading <-- here it stops and i get 302 response
    console.log(err)  <-- dosen't  print the error
      return
    }

But on the localhost:/8080 it works so i don't have acces to the error

**Comment by mxdi9i7** [comment]
similar issue, my windows machines runs the app with no problem with fields upload, but when on ubuntu server, it gives me a 500 error
{ Error: ENOENT: no such file or directory, open 'asset/icon/avatar-2018-03-20T14-46-32.565Z'
errno: -2,
 code: 'ENOENT',
 syscall: 'open',
 path: 'asset/icon/avatar-2018-03-20T14-46-32.565Z',
storageErrors: [] }

**Comment by LinusU** [comment]
@mxdi9i7 could it be that the folder `asset/icon/` doesn't exists?

**Comment by mxdi9i7** [comment]
@LinusU  Thanks for responding. I've found the problem but cannot seem to solve it:
I'm running a node server with pm2 on a ubuntu 14 server, every part of my application works as usual except one api that accepts an image and saves it on the server. It throws a 500 server error and prompts that the path is not found, even when the path is correct and exists in the server.

When I stopped the pm2 process and used npm to run the node server on my remote ubuntu server, the api works again. It seems like it only crashes when running with a pm2 process. However, there are many parts of my server that accepts images with multer, this is the only one that's acting like this.

 It may be a problem with pm2, but I did not find any issue related to it whatsoever. It may be a problem with multer, because every other image uploading api functions normally in the pm2 process.

**Comment by LinusU** [comment]
@mxdi9i7 could it be that PM2 uses another working directory for executing your program?

Could you try and replace `asset/icon/` with something like: `path.join(__dirname, 'asset/icon/')`?

**Comment by mxdi9i7** [comment]
@LinusU  It worked perfectly. Thank you so much :)

**Comment by LinusU** [comment]
Great!

**Comment by MuhammadFASEEH2002** [comment]
> [@mxdi9i7](https://github.com/mxdi9i7) could it be that PM2 uses another working directory for executing your program?
> 
> Could you try and replace `asset/icon/` with something like: `path.join(__dirname, 'asset/icon/')`?

I am using the same but still getting the issue
