### ISSUE TITLE
How to display error message of multer on frontend ?

### ISSUE THREAD

**Issue by shubham9195** [expressjs/multer#603]
```js
var upload = multer({
	limits: { fileSize: 5 *1024 * 1024 },
	fileFilter: (req, file, cb) => {
		// console.log(file);
	  var filetypes = /jpeg|jpg|png/;
	  var mimetype = filetypes.test(file.mimetype);
	  if (!mimetype) {
		cb('Only jpeg/jpg/png images allowed', null)
		
	  }
	  	cb(null, true)
	},
```

**Comment by LinusU** [comment]
This question is a bit too broad to ask here. You want to use the standard express error handling as documented here: https://expressjs.com/en/guide/error-handling.html

If you need more help, I would recommend posting on StackOverflow...

-----

Also, two small problems with your code:

1. When the mimetype is invalid you are calling `cb` twice. Insert an early return to fix it:

  ```diff
  - cb('Only jpeg/jpg/png images allowed', null)
  + return cb('Only jpeg/jpg/png images allowed', null)
  ```

2. You are calling `cb` with a string instead of an error. While this might seem to work, it can break a lot of error handlers that expect an `Error` instance:

  ```diff
  - return cb('Only jpeg/jpg/png images allowed', null)
  + return cb(new Error('Only jpeg/jpg/png images allowed'))
  ```
