### ISSUE TITLE
Validate image ratio before uploading

### ISSUE THREAD

**Issue by alinaboghiu** [expressjs/multer#632]
I am looking for a way to get the image height and width in order to validate the ratio before uploading it with multer to S3. 

The `fileFilter` function feels like the right place to do this, however it doesn't give access to the entire file, it only seems to hold a subset of attributes, like `originalName` and `mimetype.` 

Would it be possible to get access to the entire file before uploading it?

**Comment by LinusU** [comment]
> Would it be possible to get access to the entire file before uploading it?

Unfortunately this kind of contradicts itself, in order to access the file the client has to upload it first.

Basically, you cannot do this in `fileFilter` since that is run before we have started accepting the bytes of the file. You'll have to upload it into a temporary space, then validate, and the move/send to another place.

Hope this helps ☺️

**Comment by jonchurch** [comment]
Closing as resolved 📸
