### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pawanvivekananda** [expressjs/multer#639]
Memory leak in upload file in memory.

const multer = require('multer');
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

upload.any().

Ram memory not released.

**Comment by pawanvivekananda** [comment]
I am upload 200mb of video file with above setting.

Ram memory is increasing to 300 mb more but its not releasing back once the request i finished.

**Comment by LinusU** [comment]
Have you tried running Node with `--expose-gc` and triggered GC-runs after the upload finishes?

Also, how are you measuring ram usage? You should use the builtin tools to ask v8 how much memory it uses, because it will probably not free it back to the system unless it feels that it really has too.

I'd be happy to reopen this if you could post some more info ☺️
