### ISSUE TITLE
Can multer wait for validation from express-validation?

### ISSUE THREAD

**Issue by florianpeninon** [expressjs/multer#661]
Hi there,

I was wondering if it was possible to have `multer` wait to execute the upload until `express-validation` validate the request.

### Code Sample
```javascript
const express = require('express')
const bodyParser = require('body-parser')
const multer = require('multer')
const validate = require('express-validation')
const Joi = require('joi')

const app = express()

const upload = multer({ ... })
const signupValidation = {
  body: {
    email: Joi.string().required(),
    password: Joi.string().required(),
  }
}

app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())

app.post('/signup', upload.single('picture'), validate(signupValidation), myController)

app.listen(8000, () => { console.log('Listening on 8000') })
```

I'm currently using `multer` and `express-validation` as shown above. Unfortunately, the upload takes place before the validation and swapping the two leads to an error (probably due to the multipart body).

Any advice on how to approach this?

**Comment by LinusU** [comment]
Unfortunately, the multipart form-data contains the body fields and files mixed, and thus `req.file` and `req.body` will be populated at the same time. That means that you have to run the validation after Multer...

**Comment by agustinl** [comment]
It would be helpful if this is clarified somewhere in the guide.

> That means that you have to run the validation after Multer...

![image](https://user-images.githubusercontent.com/6640773/58851486-52c76c80-8669-11e9-9504-9e479f756ced.png)

![image](https://user-images.githubusercontent.com/6640773/58851476-4cd18b80-8669-11e9-8708-9f36a07242a8.png)

Otherwise `errors.array()` return `undefined` in value parameter. And its disconcertant haha

![image](https://user-images.githubusercontent.com/6640773/58851421-172ca280-8669-11e9-850c-764477692fc7.png)

![image](https://user-images.githubusercontent.com/6640773/58851427-1dbb1a00-8669-11e9-9dcc-ef7e999817f2.png)


Regards!

**Comment by syedzubairahmed001** [comment]
I managed to solve this problem using formidable + multer + validtor(npm package) setup.
i first parsed the data using formidable then validate the fields then based on the validation i decide whether i need to upload it or not.
I hope this helps, a lot of work though :)

**Comment by syedzubairahmed001** [comment]
@florianpeninon  I managed to solve this problem using formidable + multer + validtor(npm package) setup.
i first parsed the data using formidable then validate the fields then based on the validation i decide whether i need to upload it or not.
I hope this helps, a lot of work though :)
