### ISSUE TITLE
Question : How to Cancel the ongoing File Upload with Multer ? 

### ISSUE THREAD

**Issue by dipakkr** [expressjs/multer#686]
I am using REST API. 

If I am able to cancel the upload, will there be any partial uploaded content in the database?

**Comment by Ncifra** [comment]
@dipakkr The way you would do it, would be that first the file gets saved in a Buffer, and also it can be stored in a URI location in the server depending on your configuration. 
After that, it's the second step from you that saves it in the database, but logically this would mean after the "multipart..." request has finished, and multer has fully received and interpreted the request.

With the above said, depending on the library you are using to send the request, you would need to "abort" the request to "Cancel the ongoing File Upload with Multer". And this would mean that by default you wouldn't have stored anything in the database, since that would need to happen **after** the request as fully finished.

**Comment by dipakkr** [comment]
@Ncifra suppose I intiated a upload request, the files are stored on server in chunks. If I cancel the ongoing upload, the uploaded chunks are still on server.  How can I remove this ?

**Comment by Ncifra** [comment]
> If I cancel the ongoing upload, the uploaded chunks are still on server.

Are you sure of this? Because we need to know how busboy or the most primitive module itself that handles the stream, deals with this. I think, in my opinion at least, there should be some kind of control for unfinished streams, especially these user cancelled.

According to: https://github.com/expressjs/multer/blob/master/lib/make-middleware.js, on line 60, we have:
```
    function abortWithError (uploadError) {
      if (errorOccured) return
      errorOccured = true

      pendingWrites.onceZero(function () {
        function remove (file, cb) {
          storage._removeFile(req, file, cb)
        }

        removeUploadedFiles(uploadedFiles, remove, function (err, storageErrors) {
          if (err) return done(err)

          uploadError.storageErrors = storageErrors
          done(uploadError)
        })
      })
}
```

This is the function that cleans uploaded files, so you need not worry about this. As for the streams themselves, I think the discussion is over here:
https://github.com/mscdex/busboy/issues/130

`unpipe` seems to release the resources for the garbage collector, and it is called here on done():
https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L49

So in theory, except for the case where you actually have identified unfinished streams/files, I think they are cleaned up for you on the background.

**Comment by aryabharat** [comment]
Hi
I have the same issue, now working on an API which will allow the user to upload a large file to the server, n I'm using multer for this now how can user stop a file upload when any wrong file has been selected?
