### ISSUE TITLE
Ensure that req.body is populated

### ISSUE THREAD

**Issue by djpalumbo** [expressjs/multer#698]
Is there any way to ensure that `req.body` is populated before/upon reaching DiskStorage? Currently, I've written my route to work in accordance to [this StackOverflow post](https://stackoverflow.com/a/43197040/10177962), which recommends sending the file last. I'm happy to say that this solution works. However, I'd much rather be able to structure requests in a way that's agnostic to any ordering/timing issues, so as to avoid any confusion.

**Comment by LinusU** [comment]
Unfortunately, this is not possible since when the fields are after the files in the request, they haven't been read by the time the file is going to be handed over to DiskStorage.

This is solved/worked around in v2 where you get a stream for each file, which you can use after all the fields have been parsed. See here: #399
