### ISSUE TITLE
No way to create folders before upload

### ISSUE THREAD

**Issue by Rc85** [expressjs/multer#729]
multer ^1.3.1

I'm using diskStorage to define the destination where I upload my files. The issue is that I want to dynamically create folders based some parameters where the file goes. For example `./files/{id}/{anotherId}`. It's possible to do this if the params are saved in the request session, but this solution is not a good practice.

    const jobFileStorage = multer.diskStorage({
        destination: (req, file, cb) => {
            let dir = `./job_files`;

            cb(null, dir);
        },
        filename: (req, file, cb) => {
            cb(null, `${file.originalname}`);
        }
    });

In the above example, req.body returns `undefined` and there is no way to check if `./job_files/1` exists. This means that there is no way to check if a file exists before uploading it to the server.  I have to do all my checks in my middleware and that is AFTER the upload is complete.

If there is a way to check before upload, please advise. Otherwise, consider implementing it?

**Comment by LinusU** [comment]
This has been brought up a number of times before, and is a limitation of the `multipart/form-data` format. The file is simply sent from the browser before the field.

If you control the client, you can reorder the fields with JavaScript so that the fields comes before the file.

You can also look at the new API in the 2.x alpha, #399, which works around this by handling the files in a temporary space for you and giving you readable streams in your route handler.

**Comment by Hatuw** [comment]
here is my code.

```javascript
const mkdirp = require('mkdirp');
destination: function (req, file, cb) {
    const dest = `data/${getTime()}/`;
    mkdirp(dest, function (err) {
        if (err) console.error(`fail to mkdir ${dest}`);
        return cb(null, dest);
    })
}
```
