### ISSUE TITLE
Multer Error Handling + MongoDB

### ISSUE THREAD

**Issue by velcis** [expressjs/multer#744]
I have my routing here: 
router.post('/post', (req, res, next) => {
    upload(req, res, function (err) {
        if (err instanceof multer.MulterError) {
            res.send(err)
          } else if (err) {
            res.send(err)
        }
        imagens_controller.enviar_imagem()
    })
});

but my function enviar_imagem() is not receiving the req.body params...

but if i set this: 
router.post('/post', multer(multerConfig).single("file"), imagens_controller.enviar_imagem });

it works normal, but i cant handle the errors.

any clue??

**Comment by agustinl** [comment]
Hi @velcis , mmm maybe because multer only works with req.files and not req.body.
When you write this code `router.post('/post', multer(multerConfig).single("file"), imagens_controller.enviar_imagem });` you write two separate middlewares.

First, execute `multer`, and if is ok, next execute `imagens_controller.enviar_imagem`

What errors you try to handle?

👋
