### ISSUE TITLE
Abort uplpoading file.

### ISSUE THREAD

**Issue by tungbk52** [expressjs/multer#95]
I'm using follow code to upload file to node js server run multer

```javascript
function uploadFiles(url, files) {
  var formData = new FormData();

  for (var i = 0, file; file = files[i]; ++i) {
    formData.append(file.name, file);
  }

  var xhr = new XMLHttpRequest();
  xhr.open('POST', url, true);
  xhr.onload = function(e) { ... };

  xhr.send(formData);  // multipart/form-data
}
```

Now, on client I want abort uploading file use xhr.abort(), multer not continous save data, but client can't not upload more any file.

**Comment by jpfluger** [comment]
Currently not a clean method to do this.  I'd like to see smoother responsiveness with client requests myself.

**Comment by LinusU** [comment]
As I understand [the spec](https://fetch.spec.whatwg.org/#concept-fetch-terminate) the `.abort()` function will close the socket which we will detect on our end, and no more data will come thru. We won't be able to send any response since the socket will be closed.

I don't really understand your last sentence, are you saying that multer can't handle anymore requests after one client runs `.abort()`?

**Comment by jpfluger** [comment]
@LinusU is correct.  The client-server connection will be closed on xhr.abort().  My apologies. I looked at the code example as being server-side code and trying to abort multer in progress. multer.abort() does not exist.  Actually, xhr.abort() could play into the per-file strategy in our discussion for https://github.com/expressjs/multer/issues/128.

**Comment by LinusU** [comment]
As I said in my previous comment `xhr.abort` closes the socket and we won't be able to send any response at all. Please reopen if you have further clarifications/questions.
