### ISSUE TITLE
multer creates invalid folder on Windows 10.  Should multer not be used on a Windows system during testing?

### ISSUE THREAD

**Issue by 333one** [expressjs/multer#978]
**Question:** Should multer not be used on Windows?  Is it Linux only?

**Environment:** Node.js, express, multer, Windows 10

I installed multer with npm on my Windows system for testing.

In a file inside of my _controllers_ directory I added these lines up top,

```
const multer = require('multer');
const upload = multer({dest: __dirname + '../uploads/images'});
```

However after running multer a few times I noticed that it had created an invalid folder with two dots after the name,

> controllers..

This folder would not delete normally and I had to remove it using a special command from the command prompt.

> rd /s "\\\\?\\path to file"

That concerns me quite a bit.  Should I avoid it on Windows?

**Comment by dougwilson** [comment]
This is because the `__dirname` variable does not have a trailing slash (https://nodejs.org/dist/latest-v15.x/docs/api/modules.html#modules_dirname). Your string concatenation `__dirname + '../uploads/images'` results in the two `..` at the start of the string to be part of the last folder name in the `__dirname` variable. You need to either change your concatination to be `__dirname + '/../uploads/images'` or use `path.join` (https://nodejs.org/dist/latest-v15.x/docs/api/path.html#path_path_join_paths) to properly join paths like `path.join(__dirname, '../uploads/images')`.
